exp:
  num_episodes: 1000
  num_runs: 5
agent:
  gamma: 0.9
  n_steps: 10
network:
  hidden_size: 64
  hidden_activation: relu
  output_activation: softmax
  num_layers: 2
  dropout_rate: 0.1
optimizer:
  type: adam
  lr: 0.001
  lr_decay: 0.99
